#!/bin/bash
usage() {
    echo "usage: build <release version number> <build version number>"
}

if [ $# -ne 2 ]; then
    usage
    exit 1
fi

replace_cmd=""
output1=$(grep -rl --include=*.{py,js,json} 'VERSION|PYTHONHOME' .)
#echo "list: $output1"

for i in $output1; do
    if [ -f $i ]; then
        #echo "file: $i"
        if [[ "$i" == *.py ]] || [[ "$i" == *.js ]]; then
            #echo "file: *.py *.js"
            sed 's/${BUILD-VERSION}/'$1'.'$2'/g; s/${PYTHONHOME}/'$PYTHONHOME'/g' $i > $i.new
            replace_cmd=$?
        elif [[ "$i" == *.json ]]; then
            sed 's/${RELEASE-VERSION}/'$1'/g' $i > $i.new
            replace_cmd=$?
        fi

        if [ ! $replace_cmd == 0 ]; then
            echo "Could not replace *-VERSION variable in $i file." >&2
            exit 2
        fi
        mv $i.new $i
        git add $i
    fi
done

git commit -m "Build / Release version number $1.$2 created."
